name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: echo "$SSH_PRIVATE_KEY" > deploy_key && chmod 600 deploy_key

    - name: Deploy WordPress
      run: |
        chmod +x deploy.sh
        ./deploy.sh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
